---
name: Send SNS Message
description: Sends a message to an SNS Topic
inputs:
  aws_access_key_id:
    description: AWS Access Key
    required: true
  aws_secret_access_key:
    description: Secret access key
    required: true
  aws_region:
    description: AWS Region
    required: true
  sns_topic_arn:
    description: ARN of SNS topic to send to
    required: true
  message:
    description: Message to send to topic
    required: true
outputs:
  result:
    description: Result of AWS command
  result-code:
    description: Exit code
runs:
  using: docker
  image: "Dockerfile"
