---
name: Send SNS Message
description: Sends a message to an SNS Topic
inputs:
  aws-access-key-id:
    description: AWS Access Key
    required: true
  aws-secret-access-key:
    description: Secret access key
    required: true
  aws-region:
    description: AWS Region
    required: true
  sns-topic-arn:
    description: ARN of SNS topic to send to
    required: true
  message:
    description: Message to send to topic
    required: true
outputs:
  result:
    description: Result of AWS command
  result-code:
    description: Exit code
runs:
  using: docker
  image: "Dockerfile"
  env:
    AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
    AWS_REGION: ${{ inputs.aws-region }}
    MESSAGE: ${{ inputs.message }}
    SNS_TOPIC_ARN: ${{ inputs.sns-topic-arn }}
